.PHONY: clean All

All:
	@echo "----------Building project:[ Sources - Debug ]----------"
	@cd "Sources" && "$(MAKE)" -f  "Sources.mk"
clean:
	@echo "----------Cleaning project:[ Sources - Debug ]----------"
	@cd "Sources" && "$(MAKE)" -f  "Sources.mk" clean
