.PHONY: clean All

All:
	@echo "----------Building project:[ OurFirstProject - Debug ]----------"
	@cd "OurFirstProject" && "$(MAKE)" -f  "OurFirstProject.mk"
clean:
	@echo "----------Cleaning project:[ OurFirstProject - Debug ]----------"
	@cd "OurFirstProject" && "$(MAKE)" -f  "OurFirstProject.mk" clean
